name: Build Obfuscate BPB worker
on:
  push:
    branches:
      - main
  schedule:
    - cron: '3 1,13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get install -y unzip curl

      - name: Download and extract latest BPB worker
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest | grep "browser_download_url.*worker.zip" | cut -d '"' -f 4)
          wget "$LATEST_URL" -O worker.zip
          unzip -p worker.zip > origin.js
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --self-defending false \
            --simplify true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add origin.js _worker.js
          if git diff-index --quiet HEAD --; then
            echo "No changes detected, skipping commit"
          else
            git commit -m "Auto update worker files [$(date +'%Y-%m-%d %H:%M:%S')]"
            git pull --rebase origin main
            git push origin main
          fi
